### ISSUE TITLE
对“粒子发射器”的“描述”的更改建议（不成熟）		Suggested changes to the Description of Particle Emitter (immature)

### ISSUE THREAD

**Issue by cnbilinyj** [XeroAlpha/caidlist#1]
拉取请求：#2 

[`output/clib/release/vanilla.json`](/XeroAlpha/caidlist/blob/master/output/clib/release/vanilla.json)中的文件至少可以将[`L3616`](/XeroAlpha/caidlist/blob/master/output/clib/release/vanilla.json#L3616)到[`L3617`](/XeroAlpha/caidlist/blob/master/output/clib/release/vanilla.json#L3617)更改为
```
			"minecraft:arrow_spell_emitter": "斜上随机色药水粒子",
			"minecraft:balloon_gas_particle": "烟花加速尾气",
```
目前尚未完成关于所有粒子加速器的详细描述，相关内容后续将予以补充。
更改后文件内容：
[vanilla.json`(1)`](https://github.com/XeroAlpha/caidlist/files/15149495/vanilla.json)

**Comment by XeroAlpha** [comment]
暂不接受未确定规则的主观类翻译。

**Comment by cnbilinyj** [comment]
> 暂不接受未确定规则的主观类翻译。

但我已经根据实际测试判断进行补充

补充项你可以选择不采纳，但是纠错项真的是你搞反了

有伤害来源实体选择器是直接给他伤害；没有伤害来源实体选择器的反而是定义伤害来源的。

这很明显是搞反了啊
